events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip on;
    gzip_min_length 1100;
    gzip_buffers 4 8k;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/json
        image/svg+xml;

    server {
        listen 80;
        server_name eve.justedave.tv;

        root /usr/share/nginx/html;
        index index.html;

        # React SPA
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:8000/;
        }
    }
}